# This is a workflow to publish master branch changes to VSCE
name: "Release to Marketplace"

# This action will only run when a new GitHub release is published.
on:
  release:
    types: [published]

jobs:
  release:
    runs-on: "ubuntu-latest"
    steps:
      - name: "Checkout"
        uses: "actions/checkout@v2"

      - name: "Setup NodeJS"
        uses: actions/setup-node@v1

      - name: "Install Dependencies"
        run: "npm install"

      - name: "Run Tests"
        run: "xvfb-run -a npm test"

      - name: "Publish to Marketplace"
        uses: "sigma/vsce-publish-action@v0.0.2"
        with:
          vsce_token: ${{ secrets.VSCE_TOKEN }}
